{% set name = "simplesat" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 990115b1bb32a76c30b2416f645e99e61360382c795203e25ab59b26cd173749

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - attrs >=17.4.0
    - okonomiyaki >=0.16.6
    - six >=1.10.0
    - enum34

test:
  imports:
    - simplesat

about:
  home: https://github.com/enthought/sat-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'SAT solver for use in Enstaller, based on the MiniSat implementation'

extra:
  recipe-maintainers:
    - hmaarrfk
