travis:
  secure:
    BINSTAR_TOKEN: KzBlK2AFw2xVhCwX8oyNNjZGJBrmiGZ/wUaIwGvvnja296opBdyuKtAN1HqfMGJvP1XZLaMMbW8mGosvBVCDi5k5iKWC4frxJiskb3s6o9fXiFCOdyEDI7NRoUn9/o7/CKjRPXAiTA0IT2fLeOwMdRDqvSHmSs4Alrd1VCvf2KaxXJQ2ud2yOdDTVx1FQ4CmpYo1HBdbZeoEP92RbouqBHBKlrqw1k0GCxHk79ab/V4gtFFQ26szxjA4S7EJ11JkE27yQgNhtyHrZR+cNykWslqyF8MSMkTqZyYtZaA3SqBrbQO4Nmp4Z59VbuMW8moE17JFqfN1+BqlF+yorAUgkgTFi7AIdtcU+t31fKx1/bDtOpPLeoOcAGxO9f/FzEktH0+gEw/ZVKVzJzfFboja6I3WoXUu4YGSo0DSQfF9epGmtlZ8U6N+cfLZ/fiAWx8KE+orTIPxEr5PtLOVkM6aQ1zHAfR4wiOANUIYzGFM8jlTWHJ2oalOmEZvJeN2AfpBt3Gq4IKuxPaSHINBvZknI/wIID7tyAeoWrPyW/3GsEg0d+ZU6/dMEvU1Uhz9onEVfARywrXhMfkdtBxoVcwoL4Btqq5H3EQ5AbPp+fxbNJGc2DoTIb2PsIzjg3uQ+GswVJl/YX4ueE/wPrlEC0OMdkhs1WlhiVk7fSwF4DlmScc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
